mysql:
  user: root
  password: test123
  host: localhost
  port: 3306
backup:
  dataBackupDir: 'backup'
  strategiesBackup:
    - name: hang-ngay
      execFlags: ""
      cron: "* * * * * *"
      incrementalBackups:
        - every: "10s"
          take: 5
